### ISSUE TITLE
Link to our social media

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/laws-africa.github.io#12]
Twitter: http://twitter.com/@laws_africa
Youtube: https://www.youtube.com/channel/UCUFRw2pyZUq9ekMThYQ4kCQ

**Comment by longhotsummer** [comment]
Footer and Contact Us page

**Comment by longhotsummer** [comment]
LinkedIn: https://www.linkedin.com/company/laws-africa/

**Comment by AliciadW** [comment]
https://github.com/laws-africa/laws-africa.github.io/pull/16

**Comment by AliciadW** [comment]
![Screenshot 2019-05-09 at 10 19 08](https://user-images.githubusercontent.com/13785692/57438497-5cb1a780-7244-11e9-80d5-5cdff27339e3.png)
![Screenshot 2019-05-09 at 10 19 18](https://user-images.githubusercontent.com/13785692/57438499-5d4a3e00-7244-11e9-8a86-30e0d8cce8df.png)
