### ISSUE TITLE
Add Sibo and Ufuoma as contributors

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/laws-africa.github.io#13]
On the about page, underneath the core team, we need another section heading "Contributors".

It'll draw on the same 'people' collection that the team does, except that we'll need to add a new flag to all people, called "group" which can be "core" or "contributors", and then filter them as we're iterating through them. That will allow us to add new contributors via SiteLeaf.

Contributors will have:

* name
* photo
* blurb
* role
* link to profile on edit.laws.africa

**Comment by AliciadW** [comment]
https://github.com/laws-africa/laws-africa.github.io/pull/14
