### ISSUE TITLE
Blog listing and detail page

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/laws-africa.github.io#9]
* [x] link in header
* [x] listing page
* [x] blog detail page

# Listing page

The listing page should include a header image, title and lead/intro text for each blog. Three in a row (desktop) should be fine.

# Blog page

The blog page can look a bit like Medium: title, author, main image, text. It can build on the `slim` layout from our site (if necessary), so that the content is in a narrower container than the default bootstrap container. Correct social media metadata headers, too.

I've got some basic templates from bootstrapshuffle.com which we can use as starting points.

**Comment by AliciadW** [comment]
https://github.com/laws-africa/laws-africa.github.io/pull/10

**Comment by AliciadW** [comment]
#11
